BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "ctibsp"
BBFILE_PATTERN_ctibsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_ctibsp = "50"

LAYERVERSION_ctibsp = "4"
LAYERSERIES_COMPAT_ctibsp = "scarthgap styhead walnascar"
